### ISSUE TITLE
UTF-16 support

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/CairoMakie.jl#63]
For proper UTF-16 support, it looks like we can't use Cairo's text API - we may have to switch to glyphs.

**Comment by SimonDanisch** [comment]
For what do we need `utf-16`? We do seem to support `utf-8`, no?

**Comment by asinghvi17** [comment]
Yes, utf8 is fine - GLMakie supports utf16, though, and a lot of mathematical stuff, italic and feature characters, etc lie bbn in utf16.  I don't think UnicodeFun would work without it, for instance.

**Comment by SimonDanisch** [comment]
How did you come to that conclusion? utf-8 should have all the same symbols available, no?

**Comment by asinghvi17** [comment]
Nope, not for mathematical characters. I ran into this when using characters like `\itv` in a CairoMakie plot to approximate LaTeX.  That's far easier than specifying the font for each character.

**Comment by SimonDanisch** [comment]
But how did you determine this is an utf-8 problem?

**Comment by SimonDanisch** [comment]
If i'm not missing anything, Julia strings are utf-8 encoded, so if it works fine in a Julia string, then it's not an utf-8 problem! Secondly, I'm 90% sure, that utf-8 and utf16 are able to encoded the same range of symbols

**Comment by asinghvi17** [comment]
Consider this plot:
```julia
text("α⬥Ξ \n\n 𝑣𝔠")
```
The first line is all UTF-8; the second is UTF-16.

This plots as expected in GLMakie:

<img width="832" alt="Screen Shot 2020-04-07 at 4 44 51  85300PM" src="https://user-images.githubusercontent.com/32143268/78663131-38949580-78ef-11ea-95f3-8ccd8f01c238.png">

but not in CairoMakie:

![iTerm2 LimKoX](https://user-images.githubusercontent.com/32143268/78663242-637ee980-78ef-11ea-9de6-1e91f8fd74e6.jpeg)

and Cairo has explicitly documented that the text API does not support anything but UTF-8 characters.

**Comment by SimonDanisch** [comment]
`The first line is all UTF-8; the second is UTF-16.`
That doesn't make any sense, since it's a julia string which is utf8!

This happens because the font doesn't support all characters ;)
In GLMakie, I don't support UTF-16, I just do extra effort, to look up a font that can represent those characters - basically ignoring the given font once you hit a character that can't be represented by the font.

**Comment by SimonDanisch** [comment]
That's the code i use for it: 
https://github.com/JuliaPlots/CairoMakie.jl/blob/5e757e10b533dc6bfdd063975de090da354f0a60/src/cairo_ext.jl#L14

**Comment by asinghvi17** [comment]
Ah, now I understand.  I think I got confused before, because DejaVu Sans seemed to have support for it when I looked online, but I must have misread it or something.  It looks like the font GLMakie is using is `"noto sans symbols regular"`, which makes sense...so I guess my font was just wrong.  Sorry to go down the rabbit hole :D

**Comment by SimonDanisch** [comment]
Yeah DejaVu Sans is weird, since it somehow should support these characters, but doesn't :D 
I'm not sure if there is a secret extended version somewhere, freetype just messes this up, or if people spread this rumour, because if you set `DejaVu` in your editor, you'll usually get good utf-8 support, but maybe the editors do similar hacks to what I do ;)

**Comment by asinghvi17** [comment]
I think the editors maintain fallback fonts, because it renders in Atom at least (which I've configured to have Noto as a fallback).
